apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment
          image: shahmeer01/job_portal_payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: global-config
            - secretRef:
                name: global-secret
            - configMapRef:
                name: payment-config
            - secretRef:
                name: payment-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004